#cloud-config
repo_update: true
repo_upgrade: all
package_upgrade: true

packages:
    - unzip
    - git
    - vim
    - tmux
    - curl
    - wget
    - zsh
    - python3-pip
    - dnf-plugins-core
    - gpg
    - unzip
    - gh
    - code

yum_repos:
    rtx-repo:
        name: RTX Repo
        baseurl: https://rtx.jdx.dev/rpm
        enabled: 1
        gpgcheck: 1
        gpgkey: http://rtx.jdx.dev/gpg-key.pub
    githubcli-archive:
        name: packages for the GitHub CLI
        baseurl: https://cli.github.com/packages/rpm
        enabled: 1
        gpgkey: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x23F3D4EA75716059
    vscode:
        name: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: 1
        gpgcheck: 1
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

users:
    - name: ssm-user
      groups: [adm, cdrom, dip, lxd, sudo, docker]
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /usr/bin/zsh

